import Link from "next/link";
import { ArrowRight, ArrowUpRight, BadgeCheck, BookOpenCheck, Building2, HeartHandshake, LockKeyhole, ReceiptText, ShieldCheck, Users } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";

const steps = [
  ["01", "Set up your parent profile", "Add your U.S. contact and address details, then create profiles for your children."],
  ["02", "Find the child's school", "Choose a participating Virginia school or request that we contact a school that is not listed."],
  ["03", "Share an invoice privately", "Upload the school's fee statement and save a draft. The invoice stays unverified until the school confirms it."]
];
const values = [
  [ShieldCheck, "Private by design", "Your account controls access to your child and invoice documents."],
  [HeartHandshake, "Clear next steps", "School selection and parent-submitted invoices are clearly marked until confirmed."],
  [Building2, "School confirmation matters", "A parent's school selection never confirms attendance or verifies an invoice."]
];
const faqs = [
  ["Can I use any school?", "You can choose a participating school in the directory. If the school is not listed, send a request for SchoolPay to contact it. A request does not add or approve a school."],
  ["Is a school connection confirmed when I select it?", "No. Your selection asks the school to confirm the connection. Attendance and invoice details remain unverified until then."],
  ["Can I apply for financing now?", "Financing decisions, offers, agreements, and payments are not available in this phase. An application draft is only a saved draft."],
  ["What invoice files can I upload?", "Upload a PDF, JPG, JPEG, or PNG file up to 4 MB. SchoolPay stores it privately and labels the amount unverified until confirmation."]
];

export default function Home() {
  return <><SiteHeader/><main>
    <section className="hero"><div className="container hero-grid"><div><span className="eyebrow">Built for U.S. parents · Virginia launch</span><h1>Keep their<br/><span>education</span> moving.</h1><p className="hero-copy">SchoolPay helps parents organize child and school information, find participating Virginia schools, securely manage tuition invoices, and save a draft for later.</p><div className="hero-actions"><Link className="button button-primary" href="/register">Create an account <ArrowRight size={16}/></Link><Link className="button button-secondary" href="/schools">Explore schools</Link></div><p className="hero-note"><ShieldCheck size={16}/> School and invoice details stay unverified until confirmed.</p></div>
      <div className="hero-art" aria-label="Illustration of a private tuition invoice awaiting school confirmation"><div className="art-wash"/><div className="hero-card"><div className="hero-card-top"><div className="mini-brand"><span className="mini-icon"><BookOpenCheck size={17}/></span>Tuition invoice</div><span className="status-pill" style={{background:"#fff5e9",color:"#93622a"}}><i style={{background:"#e9a242"}}/> Needs confirmation</span></div><div className="invoice-school"><span className="school-avatar">S</span><div><strong>School information</strong><small>Selected by a parent</small></div></div><div className="invoice-amount"><span>Outstanding amount</span><strong>$—</strong><small>Not verified by the school</small></div><div className="pay-route"><ShieldCheck size={16}/>Private document · parent account only</div><div className="card-bottom"><span>Application</span><strong>Draft only</strong></div></div><div className="floating-note one"><span className="float-icon"><ReceiptText size={15}/></span><span><strong>Start with an invoice</strong><small>Save your progress</small></span></div></div>
    </div></section>
    <section className="trust-strip"><div className="container trust-grid"><div className="trust-item"><ShieldCheck/>Parent-controlled records</div><div className="trust-item"><BadgeCheck/>School confirmation required</div><div className="trust-item"><LockKeyhole/>Private invoice documents</div><div className="trust-item"><Users/>Virginia launch area</div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">A clear path forward</span><h2>School fees, step by step.</h2><p>Keep your child's school information and tuition documents organized in one private parent account.</p></div><div className="steps-grid">{steps.map(([num,title,desc])=><article className="step-card" key={num}><span className="step-num">{num}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
    <section className="section section-tint"><div className="container"><div className="finder-panel"><div className="finder-copy"><span className="eyebrow">School directory</span><h2>Is your child's school with us?</h2><p>Search our verified directory to find a participating school.</p></div><form action="/schools" className="finder-action"><input name="q" aria-label="Search school name" placeholder="Enter a school name"/><button className="button button-primary">Search schools <ArrowRight size={15}/></button></form></div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">Why SchoolPay</span><h2>Education deserves a thoughtful plan.</h2><p>A parent experience designed around school information, private documents, and clear expectations.</p></div><div className="value-grid">{values.map(([Icon,title,desc])=><article className="value-card" key={title as string}><span className="value-icon"><Icon size={20}/></span><h3>{title as string}</h3><p>{desc as string}</p></article>)}</div><div className="security-band" style={{marginTop:26}}><span className="security-icon"><LockKeyhole size={21}/></span><div><h3>Clear and private.</h3><p>Parent and child details stay tied to the family account. School and invoice records are marked unconfirmed until reviewed.</p></div><Link className="inline-link" href="/how-it-works">How it works <ArrowUpRight size={15}/></Link></div></div></section>
    <section className="section section-tint"><div className="container"><div className="section-heading"><span className="eyebrow">A note for schools</span><h2>School confirmation comes first.</h2><p>Parents can request a connection or ask SchoolPay to contact a school. Those requests do not automatically enroll a school or verify a student's attendance.</p><Link className="inline-link" href="/for-schools">Learn about SchoolPay for schools <ArrowRight size={15}/></Link></div><div className="quote-card"><p>“Families deserve a clear process. Schools deserve a chance to confirm the information shared about them.”</p><small>The SchoolPay approach</small></div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">Questions, answered</span><h2>Good to know from the start.</h2></div><div className="faq-list">{faqs.map(([q,a])=><article className="faq-item" key={q}><h3>{q}</h3><p>{a}</p></article>)}</div><div style={{textAlign:"center",marginTop:24}}><Link className="inline-link" href="/help">Visit the Help centre <ArrowRight size={15}/></Link></div></div></section>
    <section className="section section-tint"><div className="container"><div className="cta-panel"><span className="eyebrow" style={{color:"#a8caff"}}>Your next step</span><h2>Start with your school details.</h2><p>Create a parent account, add your child, and keep their school invoice ready for confirmation.</p><Link className="button" href="/register">Create your SchoolPay account <ArrowRight size={16}/></Link></div></div></section>
  </main><SiteFooter/></>;
}
